services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway

  gateway:
    build:
      dockerfile: DockerFile
      context: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - itemservice
      - orderservice
      - paymentservice

  itemservice:
    build:
      dockerfile: DockerFile
      context: ./itemservice
    ports:
      - "3001:3001"

  orderservice:
    build:
      dockerfile: DockerFile
      context: ./orderservice
    ports:
      - "3002:3002"

  paymentservice:
    build:
      dockerfile: DockerFile
      context: ./paymentservice
    ports:
      - "3003:3003"
