services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway

  gateway:
    build:
      dockerfile: DockerFile
      context: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - itemservice
      - orderservice
      - paymentservice
      - authservice

  itemservice:
    build:
      dockerfile: DockerFile
      context: ./itemservice
    ports:
      - "3001:3001"

  orderservice:
    build:
      dockerfile: DockerFile
      context: ./orderservice
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  paymentservice:
    build:
      dockerfile: DockerFile
      context: ./paymentservice
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq

  authservice:
    build:
      dockerfile: DockerFile
      context: ./authService
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq

  cartservice:
    build:
      dockerfile: DockerFile
      context: ./CartService
    ports:
      - "3005:3005"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  rabbitmq_data:
  jenkins_home:
