services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway

  gateway:
    build:
      dockerfile: DockerFile
      context: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - itemservice
      - orderservice
      - paymentservice

  itemservice:
    build:
      dockerfile: DockerFile
      context: ./itemservice
    ports:
      - "3001:3001"

  orderservice:
    build:
      dockerfile: DockerFile
      context: ./orderservice
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  paymentservice:
    build:
      dockerfile: DockerFile
      context: ./paymentservice
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
